In [1]:
import pandas as pd
import numpy as np

In [2]:
train = pd.read_csv('./datas/tap_fun_train.csv',encoding='utf8')

In [5]:
train[train['prediction_pay_price']==0]

,user_id,register_time,wood_add_value,wood_reduce_value,stone_add_value,stone_reduce_value,ivory_add_value,ivory_reduce_value,meat_add_value,meat_reduce_value,...,pvp_battle_count,pvp_lanch_count,pvp_win_count,pve_battle_count,pve_lanch_count,pve_win_count,avg_online_minutes,pay_price,pay_count,prediction_pay_price
0,1,2018-02-02 19:47:15,20125.0,3700.0,0.0,0.0,0.0,0.0,16375.0,2000.0,...,0,0,0,0,0,0,0.333333,0.0,0,0.0
1,1593,2018-01-26 00:01:05,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0.333333,0.0,0,0.0
2,1594,2018-01-26 00:01:58,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,1.166667,0.0,0,0.0
3,1595,2018-01-26 00:02:13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,3.166667,0.0,0,0.0
4,1596,2018-01-26 00:02:46,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,2.333333,0.0,0,0.0
5,1597,2018-01-26 00:03:06,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0.166667,0.0,0,0.0
6,1598,2018-01-26 00:03:45,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,4.000000,0.0,0,0.0
7,1599,2018-01-26 00:04:11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0.666667,0.0,0,0.0
8,1600,2018-01-26 00:06:01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,1.833333,0.0,0,0.0
9,1601,2018-01-26 00:07:42,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0.500000,0.0,0,0.0
10,1602,2018-01-26 00:07:47,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0.833333,0.0,0,0.0
11,1603,2018-01-26 00:10:27,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0.000000,0.0,0,0.0
12,1604,2018-01-26 00:10:34,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,1.000000,0.0,0,0.0
13,1605,2018-01-26 00:11:19,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0.333333,0.0,0,0.0
14,1606,2018-01-26 00:13:32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,5.333333,0.0,0,0.0
15,1607,2018-01-26 00:13:41,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0.833333,0.0,0,0.0
16,1608,2018-01-26 00:15:14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,4.500000,0.0,0,0.0
17,1609,2018-01-26 00:17:14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,5.500000,0.0,0,0.0
18,1610,2018-01-26 00:17:36,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,4.666667,0.0,0,0.0
19,1611,2018-01-26 00:17:56,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0.333333,0.0,0,0.0
20,1612,2018-01-26 00:18:14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,1.500000,0.0,0,0.0
21,1613,2018-01-26 00:19:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0.666667,0.0,0,0.0
22,1614,2018-01-26 00:20:22,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0.333333,0.0,0,0.0
23,1615,2018-01-26 00:20:47,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,10.333333,0.0,0,0.0
24,1616,2018-01-26 00:22:52,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0.000000,0.0,0,0.0
26,1618,2018-01-26 00:23:52,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,1.833333,0.0,0,0.0
27,1619,2018-01-26 00:23:58,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,3.666667,0.0,0,0.0
28,1620,2018-01-26 00:24:03,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,3.500000,0.0,0,0.0
29,1621,2018-01-26 00:24:24,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,24.166667,0.0,0,0.0
30,1622,2018-01-26 00:27:25,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,2.500000,0.0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2287976,3190500,2018-02-03 14:31:26,247365.0,148707.0,0.0,0.0,9000.0,0.0,401031.0,206242.0,...,0,0,0,6,6,6,6.500000,0.0,0,0.0
2287977,3190501,2018-02-03 14:33:31,360670.0,198729.0,0.0,0.0,0.0,0.0,237400.0,115773.0,...,2,0,1,3,3,3,6.166667,0.0,0,0.0
2287978,3190502,2018-02-03 14:33:41,49862.0,18240.0,0.0,0.0,0.0,0.0,50023.0,12480.0,...,0,0,0,1,1,1,1.833333,0.0,0,0.0
2287979,3190503,2018-02-03 14:34:42,40101.0,9930.0,0.0,0.0,0.0,0.0,42305.0,7145.0,...,0,0,0,1,1,1,1.166667,0.0,0,0.0
2287980,3190504,2018-02-03 14:34:57,15500.0,3700.0,0.0,0.0,0.0,0.0,13000.0,2000.0,...,0,0,0,0,0,0,0.500000,0.0,0,0.0
2287981,3190505,2018-02-03 14:35:03,10000.0,1600.0,0.0,0.0,0.0,0.0,10000.0,900.0,...,0,0,0,0,0,0,0.333333,0.0,0,0.0
2287982,3190506,2018-02-03 14:35:16,25625.0,4700.0,0.0,0.0,0.0,0.0,36475.0,2500.0,...,0,0,0,1,1,1,1.166667,0.0,0,0.0
2287983,3190507,2018-02-03 14:36:30,417193.0,148714.0,200000.0,0.0,203000.0,0.0,820102.0,101416.0,...,0,0,0,2,2,2,3.333333,0.0,0,0.0
2287985,3190509,2018-02-03 14:37:32,412105.0,334639.0,0.0,0.0,0.0,0.0,362829.0,283117.0,...,6,0,0,2,2,2,10.333333,0.0,0,0.0
2287986,3190510,2018-02-03 14:38:07,497560.0,407662.0,0.0,0.0,0.0,0.0,211448.0,186140.0,...,0,0,0,0,0,0,6.500000,0.0,0,0.0
2287987,3190511,2018-02-03 14:39:11,110194.0,40982.0,0.0,0.0,0.0,0.0,146245.0,36041.0,...,6,3,2,1,1,1,4.166667,0.0,0,0.0
2287988,3190512,2018-02-03 14:39:20,10000.0,0.0,0.0,0.0,0.0,0.0,10000.0,0.0,...,0,0,0,0,0,0,0.000000,0.0,0,0.0
2287989,3190513,2018-02-03 14:39:27,422616.0,344190.0,0.0,0.0,0.0,0.0,879462.0,492668.0,...,0,0,0,0,0,0,9.666667,0.0,0,0.0
2287990,3190514,2018-02-03 14:41:28,328459.0,209868.0,0.0,0.0,3000.0,0.0,296805.0,147824.0,...,7,2,2,4,4,2,7.500000,0.0,0,0.0
2287991,3190515,2018-02-03 14:43:29,513885.0,382549.0,0.0,0.0,6000.0,0.0,427446.0,304766.0,...,0,0,0,7,7,6,9.833333,0.0,0,0.0
2287992,3190516,2018-02-03 14:43:47,14600.0,2100.0,0.0,0.0,0.0,0.0,12000.0,1100.0,...,0,0,0,1,1,1,0.500000,0.0,0,0.0
2287993,3190517,2018-02-03 14:44:22,190314.0,114273.0,0.0,0.0,0.0,0.0,140362.0,78286.0,...,3,3,0,2,2,2,6.333333,0.0,0,0.0
2287994,3190518,2018-02-03 14:46:19,2142278.0,2145685.0,31776.0,0.0,6000.0,0.0,2335725.0,2065428.0,...,26,20,15,23,23,15,94.833333,0.0,0,0.0
2287995,3190519,2018-02-03 14:47:38,302161.0,93379.0,200000.0,0.0,200000.0,0.0,662251.0,42021.0,...,0,0,0,0,0,0,1.333333,0.0,0,0.0
2287996,3190520,2018-02-03 14:48:34,167783.0,79367.0,0.0,0.0,0.0,0.0,352834.0,50751.0,...,3,1,0,1,1,1,6.666667,0.0,0,0.0
2287997,3190521,2018-02-03 14:48:45,462603.0,313148.0,0.0,0.0,0.0,0.0,391466.0,211257.0,...,0,0,0,0,0,0,7.000000,0.0,0,0.0
2287998,3190522,2018-02-03 14:48:50,127342.0,88717.0,0.0,0.0,0.0,0.0,130954.0,50290.0,...,0,0,0,2,2,2,3.833333,0.0,0,0.0
2287999,3190523,2018-02-03 14:48:54,261018.0,192018.0,0.0,0.0,0.0,0.0,216264.0,147264.0,...,5,4,1,4,4,4,9.833333,0.0,0,0.0
2288000,3190524,2018-02-03 14:53:49,15500.0,3700.0,0.0,0.0,0.0,0.0,13000.0,2000.0,...,0,0,0,0,0,0,0.500000,0.0,0,0.0
2288001,3190525,2018-02-03 14:53:54,70794.0,34239.0,0.0,0.0,0.0,0.0,78125.0,19548.0,...,0,0,0,1,1,1,1.833333,0.0,0,0.0
2288002,3190526,2018-02-03 14:54:10,15500.0,3700.0,0.0,0.0,0.0,0.0,13000.0,2000.0,...,0,0,0,0,0,0,0.500000,0.0,0,0.0
2288003,3190527,2018-02-03 14:55:21,10000.0,0.0,0.0,0.0,0.0,0.0,10000.0,0.0,...,0,0,0,0,0,0,0.833333,0.0,0,0.0
2288004,3190528,2018-02-03 14:56:35,131589.0,71287.0,0.0,0.0,6000.0,0.0,249356.0,39524.0,...,0,0,0,2,2,2,4.333333,0.0,0,0.0
2288005,3190529,2018-02-03 14:57:51,221984.0,122401.0,0.0,0.0,0.0,0.0,208184.0,74738.0,...,0,0,0,1,1,1,2.833333,0.0,0,0.0
2288006,3190530,2018-02-03 14:58:45,15500.0,3700.0,0.0,0.0,0.0,0.0,13000.0,2000.0,...,0,0,0,0,0,0,0.666667,0.0,0,0.0

In [6]:
train[train['prediction_pay_price']==0].head(1000).to_csv('未付费玩家.csv')

In [16]:
wff = train[train['prediction_pay_price']==0]
wff_10 = wff[wff['avg_online_minutes']>=5]

In [17]:
wff_10.count()

user_id                               526692
register_time                         526692
wood_add_value                        526692
wood_reduce_value                     526692
stone_add_value                       526692
stone_reduce_value                    526692
ivory_add_value                       526692
ivory_reduce_value                    526692
meat_add_value                        526692
meat_reduce_value                     526692
magic_add_value                       526692
magic_reduce_value                    526692
infantry_add_value                    526692
infantry_reduce_value                 526692
cavalry_add_value                     526692
cavalry_reduce_value                  526692
shaman_add_value                      526692
shaman_reduce_value                   526692
wound_infantry_add_value              526692
wound_infantry_reduce_value           526692
wound_cavalry_add_value               526692
wound_cavalry_reduce_value            526692
wound_shaman_add_value                526692
wound_shaman_reduce_value             526692
general_acceleration_add_value        526692
general_acceleration_reduce_value     526692
building_acceleration_add_value       526692
building_acceleration_reduce_value    526692
reaserch_acceleration_add_value       526692
reaserch_acceleration_reduce_value    526692
                                       ...
sr_rss_a_gather_level                 526692
sr_rss_b_gather_level                 526692
sr_rss_c_gather_level                 526692
sr_rss_d_gather_level                 526692
sr_troop_load_level                   526692
sr_rss_e_gather_level                 526692
sr_rss_e_prod_level                   526692
sr_outpost_durability_level           526692
sr_outpost_tier_2_level               526692
sr_healing_space_level                526692
sr_gathering_hunter_buff_level        526692
sr_healing_speed_level                526692
sr_outpost_tier_3_level               526692
sr_alliance_march_speed_level         526692
sr_pvp_march_speed_level              526692
sr_gathering_march_speed_level        526692
sr_outpost_tier_4_level               526692
sr_guest_troop_capacity_level         526692
sr_march_size_level                   526692
sr_rss_help_bonus_level               526692
pvp_battle_count                      526692
pvp_lanch_count                       526692
pvp_win_count                         526692
pve_battle_count                      526692
pve_lanch_count                       526692
pve_win_count                         526692
avg_online_minutes                    526692
pay_price                             526692
pay_count                             526692
prediction_pay_price                  526692
Length: 109, dtype: int64

In [4]:
train[train['prediction_pay_price']>0]

,user_id,register_time,wood_add_value,wood_reduce_value,stone_add_value,stone_reduce_value,ivory_add_value,ivory_reduce_value,meat_add_value,meat_reduce_value,...,pvp_battle_count,pvp_lanch_count,pvp_win_count,pve_battle_count,pve_lanch_count,pve_win_count,avg_online_minutes,pay_price,pay_count,prediction_pay_price
25,1617,2018-01-26 00:23:42,30000.0,97200.0,20000.0,0.0,0.0,0.0,160500.0,80392.0,...,0,0,0,0,0,0,44.666667,0.99,1,0.99
40,1632,2018-01-26 00:32:43,1111744.0,1137687.0,491331.0,790208.0,77000.0,0.0,1457249.0,708483.0,...,1,1,1,6,6,6,199.333333,2.97,3,4.96
47,1639,2018-01-26 00:40:38,249050.0,173248.0,70841.0,117012.0,55000.0,0.0,206366.0,82205.0,...,0,0,0,0,0,0,109.333333,12.97,3,12.97
86,1678,2018-01-26 01:11:11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,127.833333,0.99,1,0.99
119,1711,2018-01-26 01:47:42,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,203.166667,0.99,1,0.99
155,1747,2018-01-26 02:36:55,5475019.0,7377434.0,4926938.0,4552369.0,2507392.0,1772039.0,6040642.0,4213417.0,...,1,0,0,34,34,29,311.166667,156.88,12,166.86
171,1763,2018-01-26 03:05:08,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,13.833333,26.94,6,26.94
214,1806,2018-01-26 04:03:23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,75.166667,9.99,1,9.99
248,1840,2018-01-26 04:52:15,785351.0,1433248.0,202000.0,0.0,4000.0,0.0,816624.0,914306.0,...,2,0,1,2,2,2,76.833333,14.98,2,19.97
305,1897,2018-01-26 06:18:45,331261.0,436832.0,334718.0,442400.0,193000.0,0.0,498127.0,314368.0,...,0,0,0,4,4,4,112.833333,0.99,1,0.99
380,1972,2018-01-26 08:01:46,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,59.500000,1.98,2,1.98
381,1973,2018-01-26 08:02:21,55495770.0,12635052.0,54377106.0,12088437.0,23307953.0,7683341.0,64528810.0,9544950.0,...,2,2,2,16,16,15,143.166667,406.87,13,8982.78
390,1982,2018-01-26 08:12:39,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,4.000000,0.99,1,0.99
434,2026,2018-01-26 08:52:45,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,58.333333,0.99,1,0.99
450,2042,2018-01-26 09:14:01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,31.000000,16.96,4,16.96
481,2073,2018-01-26 09:42:34,637524.0,1077362.0,487265.0,818650.0,296764.0,94500.0,798710.0,1172188.0,...,0,0,0,1,1,1,54.833333,6.97,3,8.96
562,2154,2018-01-26 11:03:10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,79.333333,15.97,3,15.97
616,2208,2018-01-26 11:57:05,442811.0,291375.0,230000.0,0.0,239000.0,0.0,1281732.0,291375.0,...,0,0,0,18,18,18,105.166667,165.91,9,1858.58
617,2209,2018-01-26 11:57:39,4236075.0,3860615.0,3571758.0,3022640.0,1767692.0,1272694.0,3711822.0,4484808.0,...,4,3,4,24,24,24,357.000000,56.93,7,167.73
625,2217,2018-01-26 12:03:50,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,3.833333,0.99,1,0.99
630,2222,2018-01-26 12:07:39,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,26.833333,10.97,3,10.97
643,2235,2018-01-26 12:16:08,1031103.0,1020860.0,719028.0,778232.0,455100.0,0.0,1717456.0,877440.0,...,0,0,0,24,6,22,53.166667,0.99,1,1.98
716,2308,2018-01-26 13:10:11,766627.0,826967.0,604611.0,645868.0,50000.0,0.0,1030044.0,947689.0,...,0,0,0,4,4,4,210.833333,0.99,1,0.99
726,2318,2018-01-26 13:13:43,680111.0,579780.0,300510.0,335296.0,192000.0,0.0,856137.0,429376.0,...,0,0,0,17,17,17,67.333333,0.99,1,0.99
817,2409,2018-01-26 14:20:38,2389795.0,3416253.0,1507554.0,1608056.0,137250.0,280976.0,1200362.0,2137847.0,...,0,0,0,11,11,10,241.166667,1.98,2,1.98
835,2427,2018-01-26 14:36:41,2885881.0,4024323.0,1275535.0,2228671.0,492918.0,234864.0,2984983.0,3738645.0,...,32,17,27,23,23,21,551.833333,0.99,1,0.99
845,2437,2018-01-26 14:44:05,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,3.500000,0.99,1,0.99
981,2573,2018-01-26 16:20:25,1031980.0,1230634.0,723917.0,1177704.0,271622.0,230976.0,1749758.0,1712782.0,...,0,0,0,6,6,6,77.666667,0.99,1,5.98
982,2574,2018-01-26 16:21:35,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,3.000000,0.99,1,0.99
1004,2596,2018-01-26 16:38:28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,10.333333,1.98,2,1.98
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2286871,3189395,2018-02-02 16:32:36,19860796.0,19193233.0,11795962.0,10124611.0,6493802.0,2569607.0,26591809.0,18039131.0,...,51,29,36,129,129,123,378.833333,4.99,1,4.99
2286913,3189437,2018-02-02 16:58:12,4630319.0,4207478.0,1765603.0,1546024.0,851000.0,0.0,5144602.0,3485754.0,...,2,2,2,37,37,33,76.500000,0.99,1,0.99
2286961,3189485,2018-02-02 17:40:22,11930986.0,11156658.0,8251756.0,7831174.0,3350440.0,1066504.0,17442968.0,9913268.0,...,16,8,14,122,122,115,295.000000,32.95,5,76.89
2286987,3189511,2018-02-02 18:12:57,3140135.0,2607720.0,2308154.0,1504096.0,781091.0,0.0,4424502.0,1601275.0,...,0,0,0,3,3,3,40.166667,4.97,3,4.97
2287028,3189552,2018-02-02 18:46:52,3128359.0,2365601.0,1452575.0,80000.0,703000.0,0.0,5333800.0,1969726.0,...,22,18,16,11,11,10,26.666667,0.99,1,0.99
2287109,3189633,2018-02-02 19:58:56,10163108.0,8197277.0,4987665.0,3332070.0,2119385.0,127796.0,14068506.0,6211992.0,...,1,0,0,174,174,168,171.666667,10.95,5,10.95
2287140,3189664,2018-02-02 20:27:48,11397744.0,11540669.0,8343125.0,8466091.0,3561947.0,1272616.0,16748463.0,9945000.0,...,2,0,0,47,47,43,94.000000,6.97,3,6.97
2287179,3189703,2018-02-02 21:03:25,4270939.0,1956692.0,2720000.0,0.0,2303000.0,0.0,8767824.0,1263013.0,...,0,0,0,5,5,5,23.166667,6.97,3,6.97
2287262,3189786,2018-02-02 22:19:43,49458416.0,49692527.0,42136465.0,42123390.0,21068750.0,19219471.0,51575150.0,48209562.0,...,6,3,6,25,25,20,104.833333,256.83,17,256.83
2287373,3189897,2018-02-03 00:19:37,8959578.0,7992485.0,4436577.0,3852200.0,1582017.0,272764.0,11546704.0,6195047.0,...,9,1,3,21,21,4,323.166667,30.97,3,306.79
2287410,3189934,2018-02-03 01:06:29,10028844.0,8835513.0,5705770.0,4040892.0,2745000.0,0.0,13394092.0,6298507.0,...,7,0,0,18,18,17,33.500000,21.93,7,21.93
2287492,3190016,2018-02-03 03:01:28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,13.333333,0.99,1,0.99
2287517,3190041,2018-02-03 03:41:42,19169640.0,14945873.0,8923269.0,6033362.0,3804394.0,256316.0,23832022.0,13003556.0,...,26,20,24,145,145,133,341.000000,8.95,5,2962.51
2287520,3190044,2018-02-03 03:43:24,7477994.0,7530758.0,4193269.0,3588780.0,1365000.0,27000.0,12692109.0,8315411.0,...,37,10,7,36,36,29,180.166667,0.99,1,0.99
2287555,3190079,2018-02-03 04:35:38,6528791.0,7231186.0,3145660.0,3115784.0,660250.0,0.0,10702451.0,8977656.0,...,13,11,11,55,55,48,127.666667,0.99,1,17.96
2287618,3190142,2018-02-03 06:37:32,17759716.0,15247976.0,9825215.0,8517560.0,4436774.0,250376.0,25497493.0,18745701.0,...,30,11,20,30,30,26,207.666667,26.95,5,84.86
2287629,3190153,2018-02-03 06:53:03,0.0,0.0,0.0,0.0,0.0,0.0,27526.0,0.0,...,1,0,1,0,0,0,2.333333,0.00,0,0.99
2287668,3190192,2018-02-03 07:58:55,1066413.0,863808.0,20000.0,0.0,3000.0,0.0,1181453.0,840397.0,...,13,1,0,4,4,3,26.166667,0.99,1,0.99
2287708,3190232,2018-02-03 09:06:46,2658346.0,1705844.0,1000000.0,0.0,506000.0,0.0,5034609.0,2789420.0,...,0,0,0,6,6,5,11.833333,1.98,2,1.98
2287712,3190236,2018-02-03 09:12:45,6260463.0,4586736.0,1935000.0,0.0,1762000.0,0.0,11229737.0,4826001.0,...,119,64,74,163,163,160,155.500000,22.96,4,58.89
2287742,3190266,2018-02-03 09:59:53,7790637.0,7146382.0,3304671.0,2726620.0,1161000.0,0.0,8975497.0,6313195.0,...,36,30,29,45,45,42,136.333333,0.99,1,0.99
2287780,3190304,2018-02-03 10:59:29,1794487.0,221327.0,1500000.0,0.0,1506000.0,0.0,4826423.0,161863.0,...,0,0,0,13,13,10,15.166667,4.99,1,4.99
2287839,3190363,2018-02-03 12:10:21,6491961.0,3758771.0,2800000.0,0.0,2253000.0,0.0,15063484.0,7875141.0,...,0,0,0,6,6,5,13.000000,26.95,5,26.95
2287863,3190387,2018-02-03 12:33:14,10948564.0,7732858.0,6873880.0,3552064.0,3818306.0,0.0,16852765.0,5863587.0,...,8,1,2,55,55,53,180.000000,56.91,9,73.87
2287876,3190400,2018-02-03 12:47:11,19554131.0,15299280.0,11649607.0,7750674.0,5868246.0,1144016.0,28173732.0,13398733.0,...,68,47,47,158,158,142,424.333333,37.94,6,56.89
2287944,3190468,2018-02-03 13:58:39,3279816.0,3366797.0,731921.0,499296.0,226000.0,0.0,4839787.0,2895329.0,...,11,8,7,21,21,15,168.666667,0.99,1,0.99
2287946,3190470,2018-02-03 14:00:59,94586282.0,87787739.0,74282980.0,71081893.0,33097976.0,31209557.0,81641697.0,80006876.0,...,51,36,38,161,161,151,548.500000,352.77,23,932.33
2287960,3190484,2018-02-03 14:18:12,7136284.0,4755680.0,2971154.0,1284632.0,1427000.0,0.0,9909008.0,3862513.0,...,9,0,7,77,77,74,185.666667,0.99,1,20.96
2287970,3190494,2018-02-03 14:25:02,2548198.0,2127139.0,655779.0,401296.0,209000.0,0.0,2907185.0,2081544.0,...,13,5,5,18,18,18,62.000000,0.99,1,0.99
2287984,3190508,2018-02-03 14:37:21,3306382.0,2491920.0,1000000.0,0.0,509000.0,0.0,6434135.0,3854651.0,...,5,2,4,10,10,7,20.333333,1.98,2,1.98

In [7]:
train[train['prediction_pay_price']>0].head(1000).to_csv('付费玩家.csv')

In [21]:
ff =train[train['prediction_pay_price']>0]
ff_5 = ff[ff['avg_online_minutes']<=1]
ff_5.count()

user_id                               349
register_time                         349
wood_add_value                        349
wood_reduce_value                     349
stone_add_value                       349
stone_reduce_value                    349
ivory_add_value                       349
ivory_reduce_value                    349
meat_add_value                        349
meat_reduce_value                     349
magic_add_value                       349
magic_reduce_value                    349
infantry_add_value                    349
infantry_reduce_value                 349
cavalry_add_value                     349
cavalry_reduce_value                  349
shaman_add_value                      349
shaman_reduce_value                   349
wound_infantry_add_value              349
wound_infantry_reduce_value           349
wound_cavalry_add_value               349
wound_cavalry_reduce_value            349
wound_shaman_add_value                349
wound_shaman_reduce_value             349
general_acceleration_add_value        349
general_acceleration_reduce_value     349
building_acceleration_add_value       349
building_acceleration_reduce_value    349
reaserch_acceleration_add_value       349
reaserch_acceleration_reduce_value    349
                                     ...
sr_rss_a_gather_level                 349
sr_rss_b_gather_level                 349
sr_rss_c_gather_level                 349
sr_rss_d_gather_level                 349
sr_troop_load_level                   349
sr_rss_e_gather_level                 349
sr_rss_e_prod_level                   349
sr_outpost_durability_level           349
sr_outpost_tier_2_level               349
sr_healing_space_level                349
sr_gathering_hunter_buff_level        349
sr_healing_speed_level                349
sr_outpost_tier_3_level               349
sr_alliance_march_speed_level         349
sr_pvp_march_speed_level              349
sr_gathering_march_speed_level        349
sr_outpost_tier_4_level               349
sr_guest_troop_capacity_level         349
sr_march_size_level                   349
sr_rss_help_bonus_level               349
pvp_battle_count                      349
pvp_lanch_count                       349
pvp_win_count                         349
pve_battle_count                      349
pve_lanch_count                       349
pve_win_count                         349
avg_online_minutes                    349
pay_price                             349
pay_count                             349
prediction_pay_price                  349
Length: 109, dtype: int64

### 特征分析

In [8]:
train.describe()

,user_id,wood_add_value,wood_reduce_value,stone_add_value,stone_reduce_value,ivory_add_value,ivory_reduce_value,meat_add_value,meat_reduce_value,magic_add_value,...,pvp_battle_count,pvp_lanch_count,pvp_win_count,pve_battle_count,pve_lanch_count,pve_win_count,avg_online_minutes,pay_price,pay_count,prediction_pay_price
count,2.288007e+06,2.288007e+06,2.288007e+06,2.288007e+06,2.288007e+06,2.288007e+06,2.288007e+06,2.288007e+06,2.288007e+06,2.288007e+06,...,2.288007e+06,2.288007e+06,2.288007e+06,2.288007e+06,2.288007e+06,2.288007e+06,2.288007e+06,2.288007e+06,2.288007e+06,2.288007e+06
mean,1.529543e+06,4.543069e+05,3.698433e+05,1.897788e+05,1.376074e+05,8.075623e+04,3.613170e+04,5.855155e+05,3.548102e+05,7.538954e+04,...,2.148313e+00,1.059639e+00,9.838589e-01,2.844738e+00,2.832409e+00,2.556749e+00,1.020749e+01,5.346691e-01,5.770699e-02,1.793146e+00
std,9.399393e+05,4.958667e+06,3.737720e+06,4.670620e+06,3.370166e+06,2.220540e+06,1.782499e+06,5.868629e+06,3.400632e+06,9.662892e+05,...,1.167797e+01,9.074459e+00,8.951280e+00,1.276245e+01,1.271820e+01,1.184737e+01,3.895946e+01,2.263835e+01,7.090886e-01,8.846303e+01
min,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,7.499925e+05,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,5.000000e-01,0.000000e+00,0.000000e+00,0.000000e+00
50%,1.419095e+06,4.203800e+04,9.830000e+03,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,3.458700e+04,6.470000e+03,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.833333e+00,0.000000e+00,0.000000e+00,0.000000e+00
75%,2.299006e+06,1.531180e+05,9.855700e+04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.360010e+05,6.605400e+04,0.000000e+00,...,1.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,4.833333e+00,0.000000e+00,0.000000e+00,0.000000e+00
max,3.190530e+06,1.239962e+09,7.995875e+08,1.214869e+09,7.962378e+08,5.744961e+08,4.481972e+08,1.470644e+09,8.889537e+08,2.637228e+08,...,2.054000e+03,2.051000e+03,1.904000e+03,5.090000e+02,5.090000e+02,4.880000e+02,2.049667e+03,7.457950e+03,1.050000e+02,3.297781e+04

### 相关性分析

一般情况下，当Pearson相关系数低于0.4，则表明变量之间存在弱相关关系
当Pearson相关系数在0.4~0.6之间，则说明变量之间存在中度相关关系
当相关系数在0.6以上时，则反映变量之间存在强相关关系。
经过对比发现，PE与RH之间的为弱相关关系，故不考虑将该变量纳入模型。
当然，变量之间不存在线性关系并不代表不存在任何关系，可能是二次函数关系、对数关系等，所以一般还需要进行检验和变量转换。

In [ ]:
a = train.corrwith(train.prediction_pay_price)
type(a)

In [37]:
b = a[a>=0.2]
b.index

Index(['wood_add_value', 'wood_reduce_value', 'stone_add_value',
       'stone_reduce_value', 'ivory_add_value', 'ivory_reduce_value',
       'meat_add_value', 'meat_reduce_value', 'magic_add_value',
       'magic_reduce_value', 'infantry_add_value', 'cavalry_add_value',
       'general_acceleration_add_value', 'general_acceleration_reduce_value',
       'building_acceleration_add_value', 'building_acceleration_reduce_value',
       'reaserch_acceleration_add_value', 'reaserch_acceleration_reduce_value',
       'training_acceleration_add_value', 'training_acceleration_reduce_value',
       'treatment_acceleraion_add_value', 'sr_infantry_atk_level',
       'sr_cavalry_atk_level', 'sr_shaman_atk_level',
       'sr_infantry_tier_3_level', 'sr_cavalry_tier_3_level',
       'sr_shaman_tier_3_level', 'sr_troop_defense_level',
       'sr_infantry_def_level', 'sr_cavalry_def_level', 'sr_shaman_def_level',
       'sr_infantry_hp_level', 'sr_cavalry_hp_level', 'sr_shaman_hp_level',
       'sr_infantry_tier_4_level', 'sr_cavalry_tier_4_level',
       'sr_shaman_tier_4_level', 'sr_rss_c_prod_level',
       'sr_rss_e_gather_level', 'sr_outpost_tier_3_level',
       'sr_alliance_march_speed_level', 'sr_pvp_march_speed_level',
       'sr_gathering_march_speed_level', 'sr_outpost_tier_4_level',
       'pay_price', 'pay_count', 'prediction_pay_price'],
      dtype='object')

In [41]:
formula = 'prediction_pay_price'+"~"+"+".join(b.index[:-1])
formula

'prediction_pay_price~wood_add_value+wood_reduce_value+stone_add_value+stone_reduce_value+ivory_add_value+ivory_reduce_value+meat_add_value+meat_reduce_value+magic_add_value+magic_reduce_value+infantry_add_value+cavalry_add_value+general_acceleration_add_value+general_acceleration_reduce_value+building_acceleration_add_value+building_acceleration_reduce_value+reaserch_acceleration_add_value+reaserch_acceleration_reduce_value+training_acceleration_add_value+training_acceleration_reduce_value+treatment_acceleraion_add_value+sr_infantry_atk_level+sr_cavalry_atk_level+sr_shaman_atk_level+sr_infantry_tier_3_level+sr_cavalry_tier_3_level+sr_shaman_tier_3_level+sr_troop_defense_level+sr_infantry_def_level+sr_cavalry_def_level+sr_shaman_def_level+sr_infantry_hp_level+sr_cavalry_hp_level+sr_shaman_hp_level+sr_infantry_tier_4_level+sr_cavalry_tier_4_level+sr_shaman_tier_4_level+sr_rss_c_prod_level+sr_rss_e_gather_level+sr_outpost_tier_3_level+sr_alliance_march_speed_level+sr_pvp_march_speed_level+sr_gathering_march_speed_level+sr_outpost_tier_4_level+pay_price+pay_count'

In [38]:
len(b.index)

47

### 接下来进行多重共线性的检查

In [42]:
from patsy import dmatrices
# 将因变量PE，自变量AT,V,AP和截距项（值为1的1维数组）以数据框的形式组合起来
y, X = dmatrices(formula, data = train, return_type='dataframe')
y

         prediction_pay_price
0                        0.00
1                        0.00
2                        0.00
3                        0.00
4                        0.00
5                        0.00
6                        0.00
7                        0.00
8                        0.00
9                        0.00
10                       0.00
11                       0.00
12                       0.00
13                       0.00
14                       0.00
15                       0.00
16                       0.00
17                       0.00
18                       0.00
19                       0.00
20                       0.00
21                       0.00
22                       0.00
23                       0.00
24                       0.00
25                       0.99
26                       0.00
27                       0.00
28                       0.00
29                       0.00
...                       ...
2287977                  0.00
2287978                  0.00
2287979                  0.00
2287980                  0.00
2287981                  0.00
2287982                  0.00
2287983                  0.00
2287984                  1.98
2287985                  0.00
2287986                  0.00
2287987                  0.00
2287988                  0.00
2287989                  0.00
2287990                  0.00
2287991                  0.00
2287992                  0.00
2287993                  0.00
2287994                  0.00
2287995                  0.00
2287996                  0.00
2287997                  0.00
2287998                  0.00
2287999                  0.00
2288000                  0.00
2288001                  0.00
2288002                  0.00
2288003                  0.00
2288004                  0.00
2288005                  0.00
2288006                  0.00

[2288007 rows x 1 columns]

### 方差膨胀因子

可以使用VIF variance inflate factor方差膨胀因子来检验多重共线性，如果VIF大于10，
则说明变量存在多重共线性。一旦发现变量之间存在多重共线性的话，可以考虑删除变量和重新选择模型（岭回归法）

In [43]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
# 构造空的数据框
vif = pd.DataFrame()
vif["VIF Factor"] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
vif["features"] = X.columns
vif

    VIF Factor                            features
0     1.155039                           Intercept
1   668.333041                      wood_add_value
2   336.238622                   wood_reduce_value
3   652.542789                     stone_add_value
4   317.054992                  stone_reduce_value
5   157.044783                     ivory_add_value
6    87.281216                  ivory_reduce_value
7    24.764563                      meat_add_value
8    30.848993                   meat_reduce_value
9    13.162490                     magic_add_value
10   12.359844                  magic_reduce_value
11    2.823629                  infantry_add_value
12    3.515905                   cavalry_add_value
13   29.782364      general_acceleration_add_value
14   23.649038   general_acceleration_reduce_value
15   21.526852     building_acceleration_add_value
16   21.994806  building_acceleration_reduce_value
17   18.438967     reaserch_acceleration_add_value
18   18.586760  reaserch_acceleration_reduce_value
19   10.663854     training_acceleration_add_value
20    9.553437  training_acceleration_reduce_value
21    3.438740     treatment_acceleraion_add_value
22    5.299488               sr_infantry_atk_level
23    6.261881                sr_cavalry_atk_level
24    5.346408                 sr_shaman_atk_level
25    4.058903            sr_infantry_tier_3_level
26    5.328218             sr_cavalry_tier_3_level
27    4.845381              sr_shaman_tier_3_level
28    4.592172              sr_troop_defense_level
29    5.706952               sr_infantry_def_level
30    6.561632                sr_cavalry_def_level
31    5.041369                 sr_shaman_def_level
32    5.359555                sr_infantry_hp_level
33    5.453421                 sr_cavalry_hp_level
34    4.651905                  sr_shaman_hp_level
35    3.007611            sr_infantry_tier_4_level
36    3.749577             sr_cavalry_tier_4_level
37    2.132115              sr_shaman_tier_4_level
38    1.569813                 sr_rss_c_prod_level
39    1.498517               sr_rss_e_gather_level
40    1.877757             sr_outpost_tier_3_level
41    2.745942       sr_alliance_march_speed_level
42    2.926236            sr_pvp_march_speed_level
43    2.909391      sr_gathering_march_speed_level
44    1.540395             sr_outpost_tier_4_level
45    7.376526                           pay_price
46    5.120242                           pay_count

In [44]:
type(vif)

pandas.core.frame.DataFrame

In [46]:
filterd_vif = vif[vif['VIF Factor']<=10]

In [47]:
filterd_vif

    VIF Factor                            features
0     1.155039                           Intercept
11    2.823629                  infantry_add_value
12    3.515905                   cavalry_add_value
20    9.553437  training_acceleration_reduce_value
21    3.438740     treatment_acceleraion_add_value
22    5.299488               sr_infantry_atk_level
23    6.261881                sr_cavalry_atk_level
24    5.346408                 sr_shaman_atk_level
25    4.058903            sr_infantry_tier_3_level
26    5.328218             sr_cavalry_tier_3_level
27    4.845381              sr_shaman_tier_3_level
28    4.592172              sr_troop_defense_level
29    5.706952               sr_infantry_def_level
30    6.561632                sr_cavalry_def_level
31    5.041369                 sr_shaman_def_level
32    5.359555                sr_infantry_hp_level
33    5.453421                 sr_cavalry_hp_level
34    4.651905                  sr_shaman_hp_level
35    3.007611            sr_infantry_tier_4_level
36    3.749577             sr_cavalry_tier_4_level
37    2.132115              sr_shaman_tier_4_level
38    1.569813                 sr_rss_c_prod_level
39    1.498517               sr_rss_e_gather_level
40    1.877757             sr_outpost_tier_3_level
41    2.745942       sr_alliance_march_speed_level
42    2.926236            sr_pvp_march_speed_level
43    2.909391      sr_gathering_march_speed_level
44    1.540395             sr_outpost_tier_4_level
45    7.376526                           pay_price
46    5.120242                           pay_count

In [63]:
feauture_list = filterd_vif['features'].values.tolist()
feauture_list.pop(0)
feauture_list

['infantry_add_value',
 'cavalry_add_value',
 'training_acceleration_reduce_value',
 'treatment_acceleraion_add_value',
 'sr_infantry_atk_level',
 'sr_cavalry_atk_level',
 'sr_shaman_atk_level',
 'sr_infantry_tier_3_level',
 'sr_cavalry_tier_3_level',
 'sr_shaman_tier_3_level',
 'sr_troop_defense_level',
 'sr_infantry_def_level',
 'sr_cavalry_def_level',
 'sr_shaman_def_level',
 'sr_infantry_hp_level',
 'sr_cavalry_hp_level',
 'sr_shaman_hp_level',
 'sr_infantry_tier_4_level',
 'sr_cavalry_tier_4_level',
 'sr_shaman_tier_4_level',
 'sr_rss_c_prod_level',
 'sr_rss_e_gather_level',
 'sr_outpost_tier_3_level',
 'sr_alliance_march_speed_level',
 'sr_pvp_march_speed_level',
 'sr_gathering_march_speed_level',
 'sr_outpost_tier_4_level',
 'pay_price',
 'pay_count']

In [56]:
len(feauture_list)

29

In [61]:
train.columns

Index(['user_id', 'register_time', 'wood_add_value', 'wood_reduce_value',
       'stone_add_value', 'stone_reduce_value', 'ivory_add_value',
       'ivory_reduce_value', 'meat_add_value', 'meat_reduce_value',
       ...
       'pvp_battle_count', 'pvp_lanch_count', 'pvp_win_count',
       'pve_battle_count', 'pve_lanch_count', 'pve_win_count',
       'avg_online_minutes', 'pay_price', 'pay_count', 'prediction_pay_price'],
      dtype='object', length=109)

In [65]:
feauture_list.append('prediction_pay_price')

In [66]:
train_f1 = train[feauture_list]

### 异常值检查

接下来进行异常点的检测,一般可以通过高杠杆值点（帽子矩阵）或DFFITS值、学生化残差、cook距离和covratio值来判断

In [67]:
import statsmodels.api as sm
formula = 'prediction_pay_price'+"~"+"+".join(feauture_list)
fit = sm.formula.ols(formula,data=train_f1).fit()
fit.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                             OLS Regression Results
================================================================================
Dep. Variable:     prediction_pay_price   R-squared:                       1.000
Model:                              OLS   Adj. R-squared:                  1.000
Method:                   Least Squares   F-statistic:                 8.430e+28
Date:                  Wed, 22 Aug 2018   Prob (F-statistic):               0.00
Time:                          17:46:38   Log-Likelihood:             4.9832e+07
No. Observations:               2288007   AIC:                        -9.966e+07
Df Residuals:                   2287976   BIC:                        -9.966e+07
Df Model:                            30
Covariance Type:              nonrobust
======================================================================================================
                                         coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------------------
Intercept                          -1.639e-12    5.7e-14    -28.758      0.000   -1.75e-12   -1.53e-12
infantry_add_value                 -2.829e-15   4.99e-17    -56.647      0.000   -2.93e-15   -2.73e-15
cavalry_add_value                   1.435e-15   7.08e-17     20.273      0.000     1.3e-15    1.57e-15
training_acceleration_reduce_value  2.417e-14   7.36e-17    328.230      0.000     2.4e-14    2.43e-14
treatment_acceleraion_add_value     1.519e-13   1.56e-15     97.187      0.000    1.49e-13    1.55e-13
sr_infantry_atk_level               -6.04e-11      5e-13   -120.837      0.000   -6.14e-11   -5.94e-11
sr_cavalry_atk_level                6.597e-12   5.61e-13     11.748      0.000     5.5e-12     7.7e-12
sr_shaman_atk_level                   1.5e-11    5.7e-13     26.324      0.000    1.39e-11    1.61e-11
sr_infantry_tier_3_level           -4.489e-10   6.64e-12    -67.636      0.000   -4.62e-10   -4.36e-10
sr_cavalry_tier_3_level             3.853e-10   7.84e-12     49.121      0.000     3.7e-10    4.01e-10
sr_shaman_tier_3_level             -1.078e-10   7.94e-12    -13.576      0.000   -1.23e-10   -9.22e-11
sr_troop_defense_level               1.43e-10   1.67e-12     85.575      0.000     1.4e-10    1.46e-10
sr_infantry_def_level              -4.923e-10   2.47e-12   -199.137      0.000   -4.97e-10   -4.87e-10
sr_cavalry_def_level               -1.363e-10   2.67e-12    -51.005      0.000   -1.41e-10   -1.31e-10
sr_shaman_def_level                -3.508e-10   2.45e-12   -143.030      0.000   -3.56e-10   -3.46e-10
sr_infantry_hp_level                2.414e-10    1.9e-12    127.331      0.000    2.38e-10    2.45e-10
sr_cavalry_hp_level                 1.852e-10   2.09e-12     88.557      0.000    1.81e-10    1.89e-10
sr_shaman_hp_level                   2.44e-10   2.04e-12    119.496      0.000     2.4e-10    2.48e-10
sr_infantry_tier_4_level            4.772e-09   2.17e-11    219.455      0.000    4.73e-09    4.81e-09
sr_cavalry_tier_4_level            -2.037e-09   2.28e-11    -89.259      0.000   -2.08e-09   -1.99e-09
sr_shaman_tier_4_level              2.952e-09   2.04e-11    144.971      0.000    2.91e-09    2.99e-09
sr_rss_c_prod_level                 2.231e-10   1.97e-12    113.381      0.000    2.19e-10    2.27e-10
sr_rss_e_gather_level              -5.341e-11   1.05e-12    -50.752      0.000   -5.55e-11   -5.13e-11
sr_outpost_tier_3_level            -5.877e-11   2.47e-12    -23.776      0.000   -6.36e-11   -5.39e-11
sr_alliance_march_speed_level        1.36e-10   2.33e-12     58.298      0.000    1.31e-10    1.41e-10
sr_pvp_march_speed_level           -1.275e-10   1.85e-12    -69.091      0.000   -1.31e-10   -1.24e-10
sr_gathering_march_speed_level     -2.517e-10   1.96e-12   -128.475      0.000   -2.56e-10   -2.48e-10
sr_outpost_tier_4_level             4.287e-09   2.84e-11    150.929      0.000    4.23e-09    4.34e-09
pay_price                          -6.262e-12   6.34e-15   -988.282      0.000   -6.27e-12   -6.25e-12
pay_count                           1.502e-11   1.58e-13     95.027      0.000    1.47e-11    1.53e-11
prediction_pay_price                   1.0000   9.48e-16   1.05e+15      0.000       1.000       1.000
==============================================================================
Omnibus:                  7736321.924   Durbin-Watson:                   1.986
Prob(Omnibus):                  0.000   Jarque-Bera (JB):   70766005296663.281
Skew:                         -59.753   Prob(JB):                         0.00
Kurtosis:                   27247.893   Cond. No.                     1.26e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.26e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [7]:
#均方误差
from sklearn.metrics import mean_squared_error
import numpy as np
pred = fit.predict()
np.sqrt(mean_squared_error(train_f1.prediction_pay_price,pred))

NameError: name 'fit' is not defined

### 离群点检查

In [ ]:
#离群点检测
outliers = fit.get_influence()
# 高杠杆值点（帽子矩阵）
#leverage = outliers.hat_matrix_diag
# dffits值
#dffits = outliers.dffits[0]
# 学生化残差df
resid_stu = outliers.resid_studentized_external
# cook距离
#cook = outliers.cooks_distance[0]
# covratio值
#covratio = outliers.cov_ratio
# 将上面的几种异常值检验统计量与原始数据集合并
#contat1 = pd.concat([pd.Series(leverage, name = 'leverage'),pd.Series(dffits, name = 'dffits'),
#                     pd.Series(resid_stu,name = 'resid_stu'),pd.Series(cook, name = 'cook'),#
#                     pd.Series(covratio, name = 'covratio'),],axis = 1)
contat1 = pd.concat([pd.Series(resid_stu,name = 'resid_stu')],axis = 1)
df_outliers = pd.concat([train_f1,contat1], axis = 1)
df_outliers

当高杠杆值点（或帽子矩阵）大于2(p+1)/n时，则认为该样本点可能存在异常（其中p为自变量的个数，n为观测的个数）；
当DFFITS统计值大于2sqrt((p+1)/n)时 ，则认为该样本点可能存在异常；当学生化残差的绝对值大于2，则认为该样本点可能存在异常；
对于cook距离来说，则没有明确的判断标准，一般来说，值越大则为异常点的可能性就越高；
对于covratio值来说，如果一个样本的covratio值离数值1越远，则认为该样本越可能是异常值。
这里我们就以学生化残差作为评判标准，因为其包含了帽子矩阵和DFFITS的信息。

### 用学生化残差计算异常点所占比例

In [6]:
# 计算异常值数量的比例
outliers_ratio = sum(np.where((np.abs(df_outliers.resid_stu)>2),1,0))/df_outliers.shape[0]
outliers_ratio

NameError: name 'df_outliers' is not defined